// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_request`, `is_zero_i32`, `perform_login`, `post_request`, `reload_http_client`, `wait_for_auth_ack`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GroupMembersQueryParams`, `SessionTokenQuery`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<BuildRegisterCodeResponse> buildRegisterCode({
  required BuildRegisterCodeRequest payload,
}) => RustLib.instance.api.crateApiAppApiBuildRegisterCode(payload: payload);

Future<OperationStatus> verifyRegisterCode({
  required VerifyRegisterCodeRequest payload,
}) => RustLib.instance.api.crateApiAppApiVerifyRegisterCode(payload: payload);

Future<LoginResult> login({
  required LoginRequest payload,
  BigInt? timeoutSecs,
}) => RustLib.instance.api.crateApiAppApiLogin(
  payload: payload,
  timeoutSecs: timeoutSecs,
);

Future<void> logout() => RustLib.instance.api.crateApiAppApiLogout();

Future<SessionValidationResult> validateSession({
  required SessionValidateRequest payload,
}) => RustLib.instance.api.crateApiAppApiValidateSession(payload: payload);

Future<OperationStatus> changePassword({
  required ChangePasswordRequest payload,
}) => RustLib.instance.api.crateApiAppApiChangePassword(payload: payload);

Future<ChangePhoneResult> changePhone({required ChangePhoneRequest payload}) =>
    RustLib.instance.api.crateApiAppApiChangePhone(payload: payload);

Future<ChangeEmailResult> changeEmail({required ChangeEmailRequest payload}) =>
    RustLib.instance.api.crateApiAppApiChangeEmail(payload: payload);

Future<OperationStatus> updateProfile({
  required UpdateProfileRequest payload,
}) => RustLib.instance.api.crateApiAppApiUpdateProfile(payload: payload);

Future<FriendListResult> getFriendList({required FriendListQuery query}) =>
    RustLib.instance.api.crateApiAppApiGetFriendList(query: query);

Future<GroupMembersResult> getGroupMembers({
  required GroupMembersQuery query,
}) => RustLib.instance.api.crateApiAppApiGetGroupMembers(query: query);

Future<GroupMemberDetailResult> getGroupMemberDetail({
  required GroupMemberDetailQuery query,
}) => RustLib.instance.api.crateApiAppApiGetGroupMemberDetail(query: query);

Future<SearchUserResult> searchUser({required SearchUserQuery query}) =>
    RustLib.instance.api.crateApiAppApiSearchUser(query: query);

Future<RecentConversationsResult> getRecentConversations({
  required RecentConversationsQuery query,
}) => RustLib.instance.api.crateApiAppApiGetRecentConversations(query: query);

class BuildRegisterCodeRequest {
  final String name;
  final String password;
  final int regType;
  final String target;

  const BuildRegisterCodeRequest({
    required this.name,
    required this.password,
    required this.regType,
    required this.target,
  });

  @override
  int get hashCode =>
      name.hashCode ^ password.hashCode ^ regType.hashCode ^ target.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuildRegisterCodeRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          password == other.password &&
          regType == other.regType &&
          target == other.target;
}

class BuildRegisterCodeResponse {
  final String regId;
  final PlatformInt64 uid;

  const BuildRegisterCodeResponse({required this.regId, required this.uid});

  @override
  int get hashCode => regId.hashCode ^ uid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuildRegisterCodeResponse &&
          runtimeType == other.runtimeType &&
          regId == other.regId &&
          uid == other.uid;
}

class ChangeEmailRequest {
  final String sessionToken;
  final String newEmail;
  final String? oldEmailCode;
  final String newEmailCode;

  const ChangeEmailRequest({
    required this.sessionToken,
    required this.newEmail,
    this.oldEmailCode,
    required this.newEmailCode,
  });

  @override
  int get hashCode =>
      sessionToken.hashCode ^
      newEmail.hashCode ^
      oldEmailCode.hashCode ^
      newEmailCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChangeEmailRequest &&
          runtimeType == other.runtimeType &&
          sessionToken == other.sessionToken &&
          newEmail == other.newEmail &&
          oldEmailCode == other.oldEmailCode &&
          newEmailCode == other.newEmailCode;
}

class ChangeEmailResult {
  final bool ok;
  final String email;

  const ChangeEmailResult({required this.ok, required this.email});

  @override
  int get hashCode => ok.hashCode ^ email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChangeEmailResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          email == other.email;
}

class ChangePasswordRequest {
  final String sessionToken;
  final String oldPassword;
  final String newPassword;

  const ChangePasswordRequest({
    required this.sessionToken,
    required this.oldPassword,
    required this.newPassword,
  });

  @override
  int get hashCode =>
      sessionToken.hashCode ^ oldPassword.hashCode ^ newPassword.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChangePasswordRequest &&
          runtimeType == other.runtimeType &&
          sessionToken == other.sessionToken &&
          oldPassword == other.oldPassword &&
          newPassword == other.newPassword;
}

class ChangePhoneRequest {
  final String sessionToken;
  final String newPhone;
  final String? oldPhoneCode;
  final String newPhoneCode;

  const ChangePhoneRequest({
    required this.sessionToken,
    required this.newPhone,
    this.oldPhoneCode,
    required this.newPhoneCode,
  });

  @override
  int get hashCode =>
      sessionToken.hashCode ^
      newPhone.hashCode ^
      oldPhoneCode.hashCode ^
      newPhoneCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChangePhoneRequest &&
          runtimeType == other.runtimeType &&
          sessionToken == other.sessionToken &&
          newPhone == other.newPhone &&
          oldPhoneCode == other.oldPhoneCode &&
          newPhoneCode == other.newPhoneCode;
}

class ChangePhoneResult {
  final bool ok;
  final String phone;

  const ChangePhoneResult({required this.ok, required this.phone});

  @override
  int get hashCode => ok.hashCode ^ phone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChangePhoneResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          phone == other.phone;
}

class FriendListQuery {
  final String sessionToken;
  final int? page;
  final int? pageSize;

  const FriendListQuery({required this.sessionToken, this.page, this.pageSize});

  @override
  int get hashCode => sessionToken.hashCode ^ page.hashCode ^ pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendListQuery &&
          runtimeType == other.runtimeType &&
          sessionToken == other.sessionToken &&
          page == other.page &&
          pageSize == other.pageSize;
}

class FriendListResult {
  final List<FriendSummary> friends;
  final int page;
  final int pageSize;
  final bool hasMore;

  const FriendListResult({
    required this.friends,
    required this.page,
    required this.pageSize,
    required this.hasMore,
  });

  @override
  int get hashCode =>
      friends.hashCode ^ page.hashCode ^ pageSize.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendListResult &&
          runtimeType == other.runtimeType &&
          friends == other.friends &&
          page == other.page &&
          pageSize == other.pageSize &&
          hasMore == other.hasMore;
}

class FriendSummary {
  final PlatformInt64 friendId;
  final String nickname;
  final String avatar;
  final String? remark;

  const FriendSummary({
    required this.friendId,
    required this.nickname,
    required this.avatar,
    this.remark,
  });

  @override
  int get hashCode =>
      friendId.hashCode ^ nickname.hashCode ^ avatar.hashCode ^ remark.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendSummary &&
          runtimeType == other.runtimeType &&
          friendId == other.friendId &&
          nickname == other.nickname &&
          avatar == other.avatar &&
          remark == other.remark;
}

class GroupMember {
  final PlatformInt64 groupId;
  final PlatformInt64 memberId;
  final String nickname;
  final String avatar;
  final int role;

  const GroupMember({
    required this.groupId,
    required this.memberId,
    required this.nickname,
    required this.avatar,
    required this.role,
  });

  @override
  int get hashCode =>
      groupId.hashCode ^
      memberId.hashCode ^
      nickname.hashCode ^
      avatar.hashCode ^
      role.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupMember &&
          runtimeType == other.runtimeType &&
          groupId == other.groupId &&
          memberId == other.memberId &&
          nickname == other.nickname &&
          avatar == other.avatar &&
          role == other.role;
}

class GroupMemberDetailQuery {
  final String sessionToken;
  final PlatformInt64 groupId;
  final PlatformInt64 memberId;

  const GroupMemberDetailQuery({
    required this.sessionToken,
    required this.groupId,
    required this.memberId,
  });

  @override
  int get hashCode =>
      sessionToken.hashCode ^ groupId.hashCode ^ memberId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupMemberDetailQuery &&
          runtimeType == other.runtimeType &&
          sessionToken == other.sessionToken &&
          groupId == other.groupId &&
          memberId == other.memberId;
}

class GroupMemberDetailResult {
  final GroupMember? member;
  final bool isFriend;

  const GroupMemberDetailResult({this.member, required this.isFriend});

  @override
  int get hashCode => member.hashCode ^ isFriend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupMemberDetailResult &&
          runtimeType == other.runtimeType &&
          member == other.member &&
          isFriend == other.isFriend;
}

class GroupMembersQuery {
  final String sessionToken;
  final PlatformInt64 groupId;
  final int? page;
  final int? pageSize;

  const GroupMembersQuery({
    required this.sessionToken,
    required this.groupId,
    this.page,
    this.pageSize,
  });

  @override
  int get hashCode =>
      sessionToken.hashCode ^
      groupId.hashCode ^
      page.hashCode ^
      pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupMembersQuery &&
          runtimeType == other.runtimeType &&
          sessionToken == other.sessionToken &&
          groupId == other.groupId &&
          page == other.page &&
          pageSize == other.pageSize;
}

class GroupMembersResult {
  final List<GroupMember> members;
  final int page;
  final int pageSize;
  final bool hasMore;

  const GroupMembersResult({
    required this.members,
    required this.page,
    required this.pageSize,
    required this.hasMore,
  });

  @override
  int get hashCode =>
      members.hashCode ^ page.hashCode ^ pageSize.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupMembersResult &&
          runtimeType == other.runtimeType &&
          members == other.members &&
          page == other.page &&
          pageSize == other.pageSize &&
          hasMore == other.hasMore;
}

class LoginRequest {
  final String password;
  final String target;
  final int deviceType;
  final String deviceId;

  const LoginRequest({
    required this.password,
    required this.target,
    required this.deviceType,
    required this.deviceId,
  });

  @override
  int get hashCode =>
      password.hashCode ^
      target.hashCode ^
      deviceType.hashCode ^
      deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginRequest &&
          runtimeType == other.runtimeType &&
          password == other.password &&
          target == other.target &&
          deviceType == other.deviceType &&
          deviceId == other.deviceId;
}

class LoginResult {
  final String token;
  final BigInt expiresAt;
  final String socketAddr;
  final String avatar;
  final String? email;
  final String? phone;
  final String name;
  final PlatformInt64 uid;

  const LoginResult({
    required this.token,
    required this.expiresAt,
    required this.socketAddr,
    required this.avatar,
    this.email,
    this.phone,
    required this.name,
    required this.uid,
  });

  @override
  int get hashCode =>
      token.hashCode ^
      expiresAt.hashCode ^
      socketAddr.hashCode ^
      avatar.hashCode ^
      email.hashCode ^
      phone.hashCode ^
      name.hashCode ^
      uid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginResult &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          expiresAt == other.expiresAt &&
          socketAddr == other.socketAddr &&
          avatar == other.avatar &&
          email == other.email &&
          phone == other.phone &&
          name == other.name &&
          uid == other.uid;
}

class OperationStatus {
  final bool ok;

  const OperationStatus({required this.ok});

  @override
  int get hashCode => ok.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OperationStatus &&
          runtimeType == other.runtimeType &&
          ok == other.ok;
}

class RecentConversation {
  final int scene;
  final PlatformInt64 conversationId;
  final PlatformInt64 targetId;
  final PlatformInt64 lastMsgId;
  final int lastMsgKind;
  final PlatformInt64 lastSenderId;
  final PlatformInt64 lastTimestamp;
  final int unreadCount;
  final PlatformInt64 updatedAt;

  const RecentConversation({
    required this.scene,
    required this.conversationId,
    required this.targetId,
    required this.lastMsgId,
    required this.lastMsgKind,
    required this.lastSenderId,
    required this.lastTimestamp,
    required this.unreadCount,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      scene.hashCode ^
      conversationId.hashCode ^
      targetId.hashCode ^
      lastMsgId.hashCode ^
      lastMsgKind.hashCode ^
      lastSenderId.hashCode ^
      lastTimestamp.hashCode ^
      unreadCount.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecentConversation &&
          runtimeType == other.runtimeType &&
          scene == other.scene &&
          conversationId == other.conversationId &&
          targetId == other.targetId &&
          lastMsgId == other.lastMsgId &&
          lastMsgKind == other.lastMsgKind &&
          lastSenderId == other.lastSenderId &&
          lastTimestamp == other.lastTimestamp &&
          unreadCount == other.unreadCount &&
          updatedAt == other.updatedAt;
}

class RecentConversationsQuery {
  final String sessionToken;
  final int? limit;
  final PlatformInt64? beforeUpdatedAt;
  final int? beforeScene;
  final PlatformInt64? beforeConversationId;

  const RecentConversationsQuery({
    required this.sessionToken,
    this.limit,
    this.beforeUpdatedAt,
    this.beforeScene,
    this.beforeConversationId,
  });

  @override
  int get hashCode =>
      sessionToken.hashCode ^
      limit.hashCode ^
      beforeUpdatedAt.hashCode ^
      beforeScene.hashCode ^
      beforeConversationId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecentConversationsQuery &&
          runtimeType == other.runtimeType &&
          sessionToken == other.sessionToken &&
          limit == other.limit &&
          beforeUpdatedAt == other.beforeUpdatedAt &&
          beforeScene == other.beforeScene &&
          beforeConversationId == other.beforeConversationId;
}

class RecentConversationsResult {
  final List<RecentConversation> conversations;
  final bool hasMore;

  const RecentConversationsResult({
    required this.conversations,
    required this.hasMore,
  });

  @override
  int get hashCode => conversations.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecentConversationsResult &&
          runtimeType == other.runtimeType &&
          conversations == other.conversations &&
          hasMore == other.hasMore;
}

class SearchUserQuery {
  final int searchType;
  final String query;

  const SearchUserQuery({required this.searchType, required this.query});

  @override
  int get hashCode => searchType.hashCode ^ query.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchUserQuery &&
          runtimeType == other.runtimeType &&
          searchType == other.searchType &&
          query == other.query;
}

class SearchUserResult {
  final UserProfile? user;

  const SearchUserResult({this.user});

  @override
  int get hashCode => user.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchUserResult &&
          runtimeType == other.runtimeType &&
          user == other.user;
}

class SessionValidateRequest {
  final String sessionToken;

  const SessionValidateRequest({required this.sessionToken});

  @override
  int get hashCode => sessionToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionValidateRequest &&
          runtimeType == other.runtimeType &&
          sessionToken == other.sessionToken;
}

class SessionValidationResult {
  final bool ok;
  final PlatformInt64 uid;
  final BigInt expiresAt;
  final String token;

  const SessionValidationResult({
    required this.ok,
    required this.uid,
    required this.expiresAt,
    required this.token,
  });

  @override
  int get hashCode =>
      ok.hashCode ^ uid.hashCode ^ expiresAt.hashCode ^ token.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionValidationResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          uid == other.uid &&
          expiresAt == other.expiresAt &&
          token == other.token;
}

class UpdateProfileRequest {
  final String sessionToken;
  final String? avatar;
  final int? gender;

  const UpdateProfileRequest({
    required this.sessionToken,
    this.avatar,
    this.gender,
  });

  @override
  int get hashCode => sessionToken.hashCode ^ avatar.hashCode ^ gender.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateProfileRequest &&
          runtimeType == other.runtimeType &&
          sessionToken == other.sessionToken &&
          avatar == other.avatar &&
          gender == other.gender;
}

class UserProfile {
  final PlatformInt64 uid;
  final String username;
  final String avatar;
  final String? email;
  final String? phone;
  final String? signature;
  final String? region;
  final int addFriendPolicy;

  const UserProfile({
    required this.uid,
    required this.username,
    required this.avatar,
    this.email,
    this.phone,
    this.signature,
    this.region,
    required this.addFriendPolicy,
  });

  @override
  int get hashCode =>
      uid.hashCode ^
      username.hashCode ^
      avatar.hashCode ^
      email.hashCode ^
      phone.hashCode ^
      signature.hashCode ^
      region.hashCode ^
      addFriendPolicy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfile &&
          runtimeType == other.runtimeType &&
          uid == other.uid &&
          username == other.username &&
          avatar == other.avatar &&
          email == other.email &&
          phone == other.phone &&
          signature == other.signature &&
          region == other.region &&
          addFriendPolicy == other.addFriendPolicy;
}

class VerifyRegisterCodeRequest {
  final String regId;
  final String code;

  const VerifyRegisterCodeRequest({required this.regId, required this.code});

  @override
  int get hashCode => regId.hashCode ^ code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerifyRegisterCodeRequest &&
          runtimeType == other.runtimeType &&
          regId == other.regId &&
          code == other.code;
}
