// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LogoutRequest`, `LogoutResult`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class LoginRequest {
  /// 登录密码
  final String password;

  /// 目标（邮箱/手机号/用户名）
  final String target;

  /// 设备类型枚举值
  final int deviceType;

  /// 设备唯一 ID
  final String deviceId;

  const LoginRequest({
    required this.password,
    required this.target,
    required this.deviceType,
    required this.deviceId,
  });

  @override
  int get hashCode =>
      password.hashCode ^
      target.hashCode ^
      deviceType.hashCode ^
      deviceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginRequest &&
          runtimeType == other.runtimeType &&
          password == other.password &&
          target == other.target &&
          deviceType == other.deviceType &&
          deviceId == other.deviceId;
}

class LoginResult {
  /// 会话 token
  final String token;

  /// token 过期时间（秒）
  final BigInt expiresAt;

  /// socket 服务地址
  final String socketAddr;

  /// 头像 URL
  final String avatar;

  /// 邮箱
  final String? email;

  /// 手机号
  final String? phone;

  /// 用户名
  final String name;

  /// UID
  final PlatformInt64 uid;

  /// 语言
  final String? language;

  /// 国家/地区
  final String? country;

  /// 昵称
  final String? nickname;

  /// 性别枚举
  final int gender;

  /// 资料版本
  final int version;

  const LoginResult({
    required this.token,
    required this.expiresAt,
    required this.socketAddr,
    required this.avatar,
    this.email,
    this.phone,
    required this.name,
    required this.uid,
    this.language,
    this.country,
    this.nickname,
    required this.gender,
    required this.version,
  });

  @override
  int get hashCode =>
      token.hashCode ^
      expiresAt.hashCode ^
      socketAddr.hashCode ^
      avatar.hashCode ^
      email.hashCode ^
      phone.hashCode ^
      name.hashCode ^
      uid.hashCode ^
      language.hashCode ^
      country.hashCode ^
      nickname.hashCode ^
      gender.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginResult &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          expiresAt == other.expiresAt &&
          socketAddr == other.socketAddr &&
          avatar == other.avatar &&
          email == other.email &&
          phone == other.phone &&
          name == other.name &&
          uid == other.uid &&
          language == other.language &&
          country == other.country &&
          nickname == other.nickname &&
          gender == other.gender &&
          version == other.version;
}

class SessionValidateRequest {
  /// 会话 token
  final String sessionToken;

  const SessionValidateRequest({required this.sessionToken});

  @override
  int get hashCode => sessionToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionValidateRequest &&
          runtimeType == other.runtimeType &&
          sessionToken == other.sessionToken;
}

class SessionValidationResult {
  /// 是否有效
  final bool ok;

  /// UID
  final PlatformInt64 uid;

  /// 过期时间（秒）
  final BigInt expiresAt;

  /// token（可能与入参一致）
  final String token;

  const SessionValidationResult({
    required this.ok,
    required this.uid,
    required this.expiresAt,
    required this.token,
  });

  @override
  int get hashCode =>
      ok.hashCode ^ uid.hashCode ^ expiresAt.hashCode ^ token.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionValidationResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          uid == other.uid &&
          expiresAt == other.expiresAt &&
          token == other.token;
}
