// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

class BuildRegisterCodeRequest {
  /// 注册密码
  final String password;

  /// 目标（邮箱/手机号）
  final String target;

  /// 可选语言
  final String? language;

  /// 可选国家
  final String? country;

  /// 可选性别
  final int? gender;

  /// 可选昵称
  final String? nickname;

  const BuildRegisterCodeRequest({
    required this.password,
    required this.target,
    this.language,
    this.country,
    this.gender,
    this.nickname,
  });

  @override
  int get hashCode =>
      password.hashCode ^
      target.hashCode ^
      language.hashCode ^
      country.hashCode ^
      gender.hashCode ^
      nickname.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuildRegisterCodeRequest &&
          runtimeType == other.runtimeType &&
          password == other.password &&
          target == other.target &&
          language == other.language &&
          country == other.country &&
          gender == other.gender &&
          nickname == other.nickname;
}

class BuildRegisterCodeResponse {
  /// 注册 ID
  final String regId;

  /// 用户 UID
  final PlatformInt64 uid;

  const BuildRegisterCodeResponse({required this.regId, required this.uid});

  @override
  int get hashCode => regId.hashCode ^ uid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuildRegisterCodeResponse &&
          runtimeType == other.runtimeType &&
          regId == other.regId &&
          uid == other.uid;
}

class VerifyRegisterCodeRequest {
  /// 注册 ID（生成注册码时返回）
  final String regId;

  /// 验证码
  final String code;

  const VerifyRegisterCodeRequest({required this.regId, required this.code});

  @override
  int get hashCode => regId.hashCode ^ code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerifyRegisterCodeRequest &&
          runtimeType == other.runtimeType &&
          regId == other.regId &&
          code == other.code;
}
