// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GroupMembersQueryParams`, `SessionTokenQuery`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

class AddFriendPayload {
  /// 目标用户 id
  final PlatformInt64 targetUid;

  /// 附言/备注，可选
  final String? reason;

  /// 对方的备注，可选
  final String? remark;

  /// 我方期望的好友昵称（可选）
  final String? nickname;

  /// 好友来源（参考 FriendRequestSource 枚举），必传
  final int source;

  const AddFriendPayload({
    required this.targetUid,
    this.reason,
    this.remark,
    this.nickname,
    required this.source,
  });

  @override
  int get hashCode =>
      targetUid.hashCode ^
      reason.hashCode ^
      remark.hashCode ^
      nickname.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddFriendPayload &&
          runtimeType == other.runtimeType &&
          targetUid == other.targetUid &&
          reason == other.reason &&
          remark == other.remark &&
          nickname == other.nickname &&
          source == other.source;
}

class UserInfoResult {
  /// UID
  final PlatformInt64 uid;

  /// 用户名
  final String name;

  /// 头像
  final String avatar;

  /// 昵称
  final String? nickname;

  /// 性别枚举
  final int gender;

  /// 国家/地区
  final String? country;

  /// 语言
  final String? language;

  /// 邮箱
  final String? email;

  /// 手机
  final String? phone;

  const UserInfoResult({
    required this.uid,
    required this.name,
    required this.avatar,
    this.nickname,
    required this.gender,
    this.country,
    this.language,
    this.email,
    this.phone,
  });

  @override
  int get hashCode =>
      uid.hashCode ^
      name.hashCode ^
      avatar.hashCode ^
      nickname.hashCode ^
      gender.hashCode ^
      country.hashCode ^
      language.hashCode ^
      email.hashCode ^
      phone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserInfoResult &&
          runtimeType == other.runtimeType &&
          uid == other.uid &&
          name == other.name &&
          avatar == other.avatar &&
          nickname == other.nickname &&
          gender == other.gender &&
          country == other.country &&
          language == other.language &&
          email == other.email &&
          phone == other.phone;
}
