[package]
name = "app_test"
version = "0.1.0"
edition = "2024"

# 仅作为端到端验证使用的测试工程，需要复用主服务的 gRPC 定义。
[dependencies]
tokio.workspace = true
tonic.workspace = true
app_api = { path = "../app_api" }
prost.workspace = true
prost-types.workspace = true

[build-dependencies]
tonic-build.workspace = true
