[database]
url = "mysql://root:73411bf9-a4a9-4a8a-9716-8935d3@127.0.0.1:3306/friend"
[redis]
url = "redis://127.0.0.1:6379/"
[server.http]
host = "127.0.0.1"
port = 8004
[server.grpc]
host = "127.0.0.1"
port = 50051
[arb]
access_token = "change-me"
host = "http://127.0.0.1:8005"
[sys]
log_leve = "warn"  #trace debug info error warn
md5_key = "0000000000000000000000000000000"

#-----------app_socket
[[app_socket]]
index = 0
pub_socket_ip = "127.0.0.1"
pub_port = 9900

#------------friend_service
[[friend_service]]
index = 0
grpc_addr = "127.0.0.1:8002"

#------------app_group_dispatcher
[[group_service]]
index = 0
grpc_addr = "127.0.0.1:8003"

#------------user_service
[user_service]
grpc_addr = "127.0.0.1:6001"

#------------message_service
[[msg_friend_nodes]]
index = 0
grpc_addr = "127.0.0.1:8002"

#------------group_service
[[msg_group_nodes]]
index = 0
grpc_addr = "127.0.0.1:8103"

