[database]
url = "mysql://root:73411bf9-a4a9-4a8a-9716-8935d3@127.0.0.1:3306/msg_group"
[server.grpc]
host = "127.0.0.1"
port = 8103
[server.http]
host = "127.0.0.1"
port = 8303
[arb.url]
host = "http://127.0.0.1:8005"
[socket]
kafka_broker = "127.0.0.1:9092"
kafka_group_id = "msg-group-dispatcher"

[sys]
log_leve = "warn"  # trace debug info error warn
