[database]
url = "mysql://root:73411bf9-a4a9-4a8a-9716-8935d3@127.0.0.1:3306/msg_group"
[server.grpc]
host = "127.0.0.1"
port = 8103
[server.http]
host = "127.0.0.1"
port = 8303
[arb]
access_token = "change-me"
host = "http://127.0.0.1:8000"

[sys]
log_leve = "warn"  # trace debug info error warn

[kafka]
broker = "127.0.0.1:9092"
group_id = "msg_group_dispatcher"
replicas = 1
#------------group_service
[group_service]
grpc_addr = "127.0.0.1:8003"
