[database]
url = "mysql://root:73411bf9-a4a9-4a8a-9716-8935d3@127.0.0.1:3306/friend"
[redis]
url = "redis://127.0.0.1:6379/"
[server.http]
host = "127.0.0.1"
port = 8004
[server.grpc]
host = "127.0.0.1"
port = 50051
[arb]
access_token = "change-me"
host = "http://127.0.0.1:8005"
[sys]
log_leve = "warn"  #trace debug info error warn
md5_key = "0000000000000000000000000000000"

#-----------app_socket
[[app_socket]]
index = 0
pub_socket_ip = "ws://127.0.0.1:8006"
pub_port = 8006
kafka_broker = "127.0.0.1:9092"
kafka_group_id = "app_socket_dispatcher"
kafka_user_name=""
kafka_password=""

#------------friend_service
[[friend_service]]
index = 0
grpc_addr = "127.0.0.1:8002"

#------------app_group_dispatcher
[[group_service]]
index = 0
grpc_addr = "127.0.0.1:8003"

#------------user_service
[[user_service]]
index = 0
grpc_addr = "127.0.0.1:6001"

#------------message_service
[[msg_friend]]
index = 0
grpc_addr = "127.0.0.1:8002"
kafka_broker = "127.0.0.1:9092"
kafka_group_id = "msg_friend_dispatcher"
kafka_user_name=""
kafka_password=""
#------------group_service
[[msg_group]]
index = 0
grpc_addr = "127.0.0.1:8103"
kafka_broker = "127.0.0.1:9092"
kafka_group_id = "msg_group_dispatcher"
kafka_user_name=""
kafka_password=""


