[database]
url = "mysql://root:73411bf9-a4a9-4a8a-9716-8935d3@127.0.0.1:3306/online"
[server.grpc]
host = "127.0.0.1"
port = 6001
[server.http]
host = "127.0.0.1"
port = 6201
[arb]
access_token = "change-me"
host = "http://127.0.0.1:8000"
[sys]
log_leve = "warn"  #trace debug info error warn
