[database]
url = "mysql://root:73411bf9-a4a9-4a8a-9716-8935d3@127.0.0.1:3306/friend"
[server.grpc]
host = "127.0.0.1"
port = 8002
[server.http]
host = "127.0.0.1"
port = 8202
[sys]
log_leve = "warn"  #trace debug info error warn

[hot_friend]
avg_value_bytes = 256
shards = 32
reserve_ratio = 0.40
max_use_ratio = 0.25
overhead_factor = 1.6
hot_ratio = 0.20
tti_secs = 60
refresh_secs = 0


#------------user_service
# [[user_service]]
# index = 0
# grpc_addr = "127.0.0.1:6001"

# #------------message_service
# [[msg_friend]]
# index = 0
# grpc_addr = "127.0.0.1:8002"

# #------------group_service
# [[msg_group]]
# index = 0
# grpc_addr = "127.0.0.1:8103"


#------------friend_service
[friend_service]
grpc_addr = "127.0.0.1:8002"
