[database]
url = "mysql://root:73411bf9-a4a9-4a8a-9716-8935d3@127.0.0.1:3306/user"
[server.grpc]
host = "127.0.0.1"
port = 6001
[server.http]
host = "127.0.0.1"
port = 6201
[arb]
access_token = "change-me"
host = "http://127.0.0.1:8000"
[sys]
log_leve = "warn"  #trace debug info error warn

[hot_online]
shards = 128
default_cc = "86"
hot_by_id_cap = 500000
hot_by_id_ttl = 300
hot_route_cap = 200000
hot_route_ttl = 120

[user_defaults]
allow_add_friend = "ANYONE"

#
#
##-----------app_socket
#[[app_socket]]
#index = 0
#kafka_broker = "127.0.0.1:9092"
#kafka_group_id = "app_socket_dispatcher"
#kafka_user_name=""
#kafka_password=""
#
#
##------------friend_service
#[[friend_service]]
#index = 0
#grpc_addr = "ws://127.0.0.1:8006"
#
##------------app_group_dispatcher
#[[group_service]]
#index = 0
#grpc_addr = "ws://127.0.0.1:8006"
#
##------------user_service
#[[user_service]]
#index = 0
#grpc_addr = "ws://127.0.0.1:8006"
#
##------------message_service
#[[msg_friend]]
#index = 0
#grpc_addr = "127.0.0.1:8006"
#
##------------group_service
#[[msg_group]]
#index = 0
#grpc_addr = "ws://127.0.0.1:8006"
