[database]
url = "mysql://root:73411bf9-a4a9-4a8a-9716-8935d3@127.0.0.1:3306/group"
[grpc]
host = "127.0.0.1"
port = 9002
[server]
host = "127.0.0.1"
port = 8002
[sys]
log_leve = "warn"  #trace debug info error warn