-- MySQL schema
CREATE TABLE IF NOT EXISTS group_member (
  group_id  BIGINT UNSIGNED NOT NULL,
  user_id   BIGINT UNSIGNED NOT NULL,
  role      TINYINT UNSIGNED NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (group_id, user_id),
  KEY idx_user_groups (user_id, group_id)
) ENGINE=InnoDB
PARTITION BY HASH(group_id) PARTITIONS 128;

CREATE TABLE IF NOT EXISTS group_meta (
  group_id  BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  member_cnt INT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
