// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetOnlineRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(bool, tag = "2")]
    pub online: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetOnlineResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CheckOnlineRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CheckOnlineResponse {
    #[prost(bool, tag = "1")]
    pub online: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckOnlineBatchRequest {
    #[prost(int64, repeated, tag = "1")]
    pub user_ids: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckOnlineBatchResponse {
    /// 索引与输入 user_ids 对齐
    #[prost(bool, repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<bool>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetStatsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStatsResponse {
    #[prost(uint64, tag = "1")]
    pub total: u64,
    #[prost(uint64, repeated, tag = "2")]
    pub per_shard: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint32, tag = "3")]
    pub max_shard_idx: u32,
    #[prost(uint64, tag = "4")]
    pub max_shard_count: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpsertSessionTokenRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(enumeration = "super::auth::DeviceType", tag = "2")]
    pub device_type: i32,
    #[prost(string, tag = "3")]
    pub device_id: ::prost::alloc::string::String,
    /// 可选：客户端上报的登录 IP/UA，便于审计
    #[prost(string, optional, tag = "4")]
    pub login_ip: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub user_agent: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpsertSessionTokenResponse {
    #[prost(string, tag = "1")]
    pub session_token: ::prost::alloc::string::String,
    /// 过期时间（毫秒时间戳）
    #[prost(uint64, tag = "2")]
    pub expires_at: u64,
    /// 若存在旧 token，则返回以便调用方通知下线
    #[prost(string, optional, tag = "3")]
    pub previous_token: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateSessionTokenRequest {
    #[prost(string, tag = "1")]
    pub session_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateSessionTokenResponse {
    #[prost(enumeration = "SessionTokenStatus", tag = "1")]
    pub status: i32,
    #[prost(int64, tag = "2")]
    pub user_id: i64,
    #[prost(enumeration = "super::auth::DeviceType", tag = "3")]
    pub device_type: i32,
    #[prost(string, tag = "4")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub expires_at: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenDeviceRef {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(enumeration = "super::auth::DeviceType", tag = "2")]
    pub device_type: i32,
    #[prost(string, tag = "3")]
    pub device_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeSessionTokenRequest {
    #[prost(string, optional, tag = "3")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(oneof = "revoke_session_token_request::Target", tags = "1, 2")]
    pub target: ::core::option::Option<revoke_session_token_request::Target>,
}
/// Nested message and enum types in `RevokeSessionTokenRequest`.
pub mod revoke_session_token_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Target {
        #[prost(string, tag = "1")]
        SessionToken(::prost::alloc::string::String),
        #[prost(message, tag = "2")]
        Device(super::TokenDeviceRef),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeSessionTokenResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, optional, tag = "2")]
    pub revoked_token: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TouchSessionTokenRequest {
    #[prost(string, repeated, tag = "1")]
    pub session_tokens: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TouchSessionTokenResponse {
    #[prost(uint32, tag = "1")]
    pub touched: u32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SessionTokenStatus {
    StsUnknown = 0,
    StsActive = 1,
    StsRevoked = 2,
    StsExpired = 3,
}
impl SessionTokenStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::StsUnknown => "STS_UNKNOWN",
            Self::StsActive => "STS_ACTIVE",
            Self::StsRevoked => "STS_REVOKED",
            Self::StsExpired => "STS_EXPIRED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STS_UNKNOWN" => Some(Self::StsUnknown),
            "STS_ACTIVE" => Some(Self::StsActive),
            "STS_REVOKED" => Some(Self::StsRevoked),
            "STS_EXPIRED" => Some(Self::StsExpired),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod online_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct OnlineServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl OnlineServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> OnlineServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> OnlineServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            OnlineServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// 设置在线/离线（幂等）
        pub async fn set_online(
            &mut self,
            request: impl tonic::IntoRequest<super::SetOnlineRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetOnlineResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/online_service.OnlineService/SetOnline",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("online_service.OnlineService", "SetOnline"));
            self.inner.unary(req, path, codec).await
        }
        /// 单查
        pub async fn check_online(
            &mut self,
            request: impl tonic::IntoRequest<super::CheckOnlineRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CheckOnlineResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/online_service.OnlineService/CheckOnline",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("online_service.OnlineService", "CheckOnline"));
            self.inner.unary(req, path, codec).await
        }
        /// 批量查
        pub async fn check_online_batch(
            &mut self,
            request: impl tonic::IntoRequest<super::CheckOnlineBatchRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CheckOnlineBatchResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/online_service.OnlineService/CheckOnlineBatch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("online_service.OnlineService", "CheckOnlineBatch"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 统计信息
        pub async fn get_stats(
            &mut self,
            request: impl tonic::IntoRequest<super::GetStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStatsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/online_service.OnlineService/GetStats",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("online_service.OnlineService", "GetStats"));
            self.inner.unary(req, path, codec).await
        }
        /// 生成/刷新设备 session token
        pub async fn upsert_session_token(
            &mut self,
            request: impl tonic::IntoRequest<super::UpsertSessionTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpsertSessionTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/online_service.OnlineService/UpsertSessionToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("online_service.OnlineService", "UpsertSessionToken"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 校验 session token 合法性
        pub async fn validate_session_token(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateSessionTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateSessionTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/online_service.OnlineService/ValidateSessionToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "online_service.OnlineService",
                        "ValidateSessionToken",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 吊销指定 token 或设备会话
        pub async fn revoke_session_token(
            &mut self,
            request: impl tonic::IntoRequest<super::RevokeSessionTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RevokeSessionTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/online_service.OnlineService/RevokeSessionToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("online_service.OnlineService", "RevokeSessionToken"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 批量刷新最后活跃时间
        pub async fn touch_session_token(
            &mut self,
            request: impl tonic::IntoRequest<super::TouchSessionTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TouchSessionTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/online_service.OnlineService/TouchSessionToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("online_service.OnlineService", "TouchSessionToken"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
