// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class FriendEntity {
  final PlatformInt64? id;
  final PlatformInt64 friendId;
  final String avatar;
  final String? alias;
  final String? remark;
  final PlatformInt64 createdAt;

  const FriendEntity({
    this.id,
    required this.friendId,
    required this.avatar,
    this.alias,
    this.remark,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      friendId.hashCode ^
      avatar.hashCode ^
      alias.hashCode ^
      remark.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendEntity &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          friendId == other.friendId &&
          avatar == other.avatar &&
          alias == other.alias &&
          remark == other.remark &&
          createdAt == other.createdAt;
}
