// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            

            class GroupRequestEntity  {
                final PlatformInt64? id;
final PlatformInt64 requestId;
final PlatformInt64 groupId;
final PlatformInt64 applicantId;
final String reason;
final PlatformInt64 createdAt;
final Int64List viaMemberIds;
final PlatformInt64? decidedAt;
final bool? approved;
final String? remark;
final Int64List approvedMemberIds;
final PlatformInt64 updatedAt;

                const GroupRequestEntity({this.id ,required this.requestId ,required this.groupId ,required this.applicantId ,required this.reason ,required this.createdAt ,required this.viaMemberIds ,this.decidedAt ,this.approved ,this.remark ,required this.approvedMemberIds ,required this.updatedAt ,});

                
                

                
        @override
        int get hashCode => id.hashCode^requestId.hashCode^groupId.hashCode^applicantId.hashCode^reason.hashCode^createdAt.hashCode^viaMemberIds.hashCode^decidedAt.hashCode^approved.hashCode^remark.hashCode^approvedMemberIds.hashCode^updatedAt.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is GroupRequestEntity &&
                runtimeType == other.runtimeType
                && id == other.id&& requestId == other.requestId&& groupId == other.groupId&& applicantId == other.applicantId&& reason == other.reason&& createdAt == other.createdAt&& viaMemberIds == other.viaMemberIds&& decidedAt == other.decidedAt&& approved == other.approved&& remark == other.remark&& approvedMemberIds == other.approvedMemberIds&& updatedAt == other.updatedAt;
        
            }
            